TRUNCATE services CASCADE;

INSERT INTO services (name, slug, short_description, full_description, image_url, is_active, display_order, price, duration_minutes) VALUES 
('General Eye Examination', 'general-eye-examination', 'Comprehensive check-up of your eye health and vision using advanced diagnostic tools.', 'Comprehensive check-up of your eye health and vision using advanced diagnostic tools.', 'http://localhost:5000/uploads/general-eye.jpg', true, 0, '50.00', 30),
('Contact Lens Fitting', 'contact-lens-fitting', 'Professional fitting and consultation for all types of contact lenses, including specialty lenses.', 'Professional fitting and consultation for all types of contact lenses, including specialty lenses.', 'http://localhost:5000/uploads/contact-lens-services.jpg', true, 1, '70.00', 45),
('Glaucoma Screening', 'glaucoma-screening', 'Advanced screening and monitoring for early detection and management of glaucoma.', 'Advanced screening and monitoring for early detection and management of glaucoma.', 'http://localhost:5000/uploads/public-eye-health.jpg', true, 2, '60.00', 30),
('DVLA Eye Test', 'dvla-eye-test', 'Certified eye testing and certification for driver licensing requirements.', 'Certified eye testing and certification for driver licensing requirements.', 'http://localhost:5000/uploads/dvla-eye-testing.jpg', true, 3, '30.00', 15),
('Binocular Vision Services', 'binocular-vision-services', 'Specialized assessment and treatment for binocular vision anomalies and eye strain.', 'Specialized assessment and treatment for binocular vision anomalies and eye strain.', 'http://localhost:5000/uploads/binocular-vision-services.jpg', true, 4, '80.00', 45),
('Corporate Eye Health', 'corporate-eye-health', 'On-site eye screenings and ergonomic consultations for corporate environments.', 'On-site eye screenings and ergonomic consultations for corporate environments.', 'http://localhost:5000/uploads/corporate-eye-health-services.jpg', true, 5, '100.00', 60),
('Low Vision Rehabilitation', 'low-vision-rehabilitation', 'Empowering patients with permanent vision loss through specialized aids and training.', 'Empowering patients with permanent vision loss through specialized aids and training.', 'http://localhost:5000/uploads/low-vision-rehabilitation.jpg', true, 6, '40.00', 60),
('Public Eye Health', 'public-eye-health', 'Dedicated community programs for preventative eye care and health awareness.', 'Dedicated community programs for preventative eye care and health awareness.', 'http://localhost:5000/uploads/public-eye-health.jpg', true, 7, '0.00', 30);
